from .dag_d_curso import DCursoFactory
from .dag_d_forma_ingresso import DFormaIngressoFactory
from .dag_d_tipo_cota import DTipoCotaFactory
from .dag_d_forma_evasao import DFormaEvasaoFactory
from .dag_d_pessoa import DPessoaFactory
from .dag_f_situacao_matricula import FSituacaoMatriculaFactory
from .dag_d_calendario import DCalendarioFactory
from .dag_d_periodos_cursados import DPeriodosCursadosFactory
